load temperature data from Grafana instead of Xively
silsha/infoscreen-v6 pull request #13
Opened 2017-07-30 18:34 UTC by Ranlvor

The Xively temperature data does not update causing
the temperature widget to show outdated data.

I suggest fixing the issue with this commit by
loading the data from kunterbunt.vm.rzl, our
local Grafana installation.

Fixes #12

2017-07-30 23:23 UTC, silsha commented
Ist das Grafana auch außerhalb des RZLs erreichbar? Das würde es einfacher machen daran weiterzuentwickeln ohne vor Ort zu sein.

2017-07-30 23:24 UTC, silsha requested changes

2017-07-30 23:24 UTC, silsha commented on jobs/grafana.rb
> +    grafana_data = HTTParty.post('http://kunterbunt.vm.rzl/api/datasources/proxy/1/render', { :body => 'target=alias(rzl.service.heizung.temp.beamerplattform%2C%20\'Temperatur_Beamerplattform\')&from
Wenn möglich durch extern erreichbare URL ersetzen.

2017-07-30 23:30 UTC, merged

2017-07-30 23:31 UTC, silsha commented
Da es den aktuellen Status verbessert merge ich das mal. Externe URL wäre trotzdem gut :3

2017-07-31 00:47 UTC, Ranlvor commented
Es gibt eine externe URL: http://rzldashboard.drachenkatze.org/

Allerdings habe ich keine Idee, wie man elegant erkennen kann, ob der Infoscreen im RZL oder außerhalb läuft um entsprechend die URL auszuwählen. Die hacky-Variante wäre immer erst die Interne versuchen und wenn die failt fallback auf externe URL. Irgendwelche besseren Ideen?

2017-07-31 16:51 UTC, silsha commented
@Ranlvor Ich denke ich würde einfach immer die externe URL verwenden. Auf der VM kann man dann ja über die hosts-Datei die lokale IP hinterlegen (oder so).